from pathlib import Path

import pandas as pd
import streamlit as st
import plotly.graph_objects as go

# -------------------------------------------------------
# PAGE
# -------------------------------------------------------

st.set_page_config(
    page_title="AI Forecast",
    layout="wide"
)

css = Path(__file__).parents[1] / "style.css"

if css.exists():
    with open(css, encoding="utf-8") as f:
        st.markdown(
            f"<style>{f.read()}</style>",
            unsafe_allow_html=True
        )

ROOT = Path(__file__).parents[2]

df = pd.read_csv(
    ROOT/"data"/"processed"/"forecast_dataset.csv"
)

# -------------------------------------------------------
# HEADER
# -------------------------------------------------------

st.title("AI Forecast")

st.caption(
    "Forecasted financial performance generated by the machine learning model."
)

st.divider()

# -------------------------------------------------------
# COMPANY
# -------------------------------------------------------

company = st.selectbox(
    "Select Company",
    sorted(df["Company"].unique()),
    key="forecast_company"
)

row = df[df["Company"] == company].iloc[0]

# -------------------------------------------------------
# KPI
# -------------------------------------------------------

current_val = row["Valuation_Million"]
future_val = row["Expected_Valuation_12M"]

current_rev = row["Estimated_Revenue_Million"]
future_rev = row["Expected_Revenue_12M"]

current_profit = row["Estimated_Profit_Million"]
future_profit = row["Expected_Profit_12M"]

current_burn = row["Estimated_Burn_Million"]
future_burn = row["Expected_Burn_12M"]

c1,c2,c3,c4 = st.columns(4)

c1.metric(
    "Forecast Valuation",
    f"${future_val:,.0f} M",
    delta=f"{((future_val-current_val)/current_val)*100:.1f}%"
)

c2.metric(
    "Forecast Revenue",
    f"${future_rev:,.0f} M",
    delta=f"{((future_rev-current_rev)/current_rev)*100:.1f}%"
)

c3.metric(
    "Forecast Profit",
    f"${future_profit:,.0f} M",
    delta=f"{((future_profit-current_profit)/current_profit)*100:.1f}%"
)

c4.metric(
    "Forecast Burn",
    f"${future_burn:,.0f} M",
    delta=f"-{((current_burn-future_burn)/current_burn)*100:.1f}%"
)

st.divider()

# -------------------------------------------------------
# BAR COMPARISON
# -------------------------------------------------------

fig = go.Figure()

fig.add_bar(
    name="Current",
    x=[
        "Revenue",
        "Profit",
        "Burn",
        "Valuation"
    ],
    y=[
        current_rev,
        current_profit,
        current_burn,
        current_val
    ]
)

fig.add_bar(
    name="Forecast",
    x=[
        "Revenue",
        "Profit",
        "Burn",
        "Valuation"
    ],
    y=[
        future_rev,
        future_profit,
        future_burn,
        future_val
    ]
)

fig.update_layout(
    barmode="group",
    title="Current vs Forecast",
    height=500
)

st.plotly_chart(
    fig,
    use_container_width=True
)

st.divider()

# -------------------------------------------------------
# FORECAST SUMMARY
# -------------------------------------------------------

summary = pd.DataFrame({

    "Metric":[
        "Current Revenue",
        "Forecast Revenue",
        "Current Profit",
        "Forecast Profit",
        "Current Burn",
        "Forecast Burn",
        "Current Valuation",
        "Forecast Valuation"
    ],

    "Value":[
        current_rev,
        future_rev,
        current_profit,
        future_profit,
        current_burn,
        future_burn,
        current_val,
        future_val
    ]

})

st.subheader("Forecast Summary")

st.dataframe(
    summary,
    use_container_width=True,
    hide_index=True
)

st.divider()

# -------------------------------------------------------
# MODEL INSIGHTS
# -------------------------------------------------------

st.subheader("Model Insights")

valuation_growth = ((future_val-current_val)/current_val)*100
revenue_growth = ((future_rev-current_rev)/current_rev)*100
burn_change = ((future_burn-current_burn)/current_burn)*100

st.write(f"""
- Forecast valuation growth: **{valuation_growth:.1f}%**
- Forecast revenue growth: **{revenue_growth:.1f}%**
- Forecast burn rate change: **{burn_change:.1f}%**
- Expected runway: **{row['Expected_Runway_12M']:.1f} months**
""")